### ISSUE TITLE
Limitation of the Iterator-based pipeline design?

### ISSUE THREAD

**Issue by raininthesun** [stanford-futuredata/macrobase#115]
It seems that the iterator-based pipeline design limits the access to the output of a node only once? 

For example, for the "DataIngester -> FeatureTransform -> OutlierClassifier -> BatchSummarizer" in BasicBatchedPipeline,  once the results of OutlierClassifier is consumed by BatchSummarizer, I cannot access the results of OutlierClassifier again by calling its next().

**Comment by pbailis** [comment]
#112 fixes this.
