### ISSUE TITLE
Remove LowMetrics

### ISSUE THREAD

**Issue by pbailis** [stanford-futuredata/macrobase#123]
@raininthesun, @mamikonyana: we discussed removing LowMetrics and instead doing a FeatureTransform on selected metrics instead. Any thoughts?

**Comment by raininthesun** [comment]
I think this is much cleaner than having low metrics. After all, the purpose of having low metric is to serve an outlier detection algorithm, which is the exact intention of our feature transform. 

BTW, I added a `    public Datum getParentDatum() {
        return parentDatum;
    }` method in Datum.java, that allows us to access the parent Datum of a Datum before a feature transform.

**Comment by mamikonyana** [comment]
I really like that idea of removing LowMetrics. We don't have to make any design changes to remove LowMetrics so I'm all for it!

I think instead of up and down arrows in the UI, we could have 2-3 frequent transforms. Or we could have even a bigger UI change

**Comment by pbailis** [comment]
Fixed in #133
