### ISSUE TITLE
Remove `inspect()` from `MBStream`

### ISSUE THREAD

**Issue by pbailis** [stanford-futuredata/macrobase#130]
This should be `drain()` instead...

**Comment by raininthesun** [comment]
drain() clears all the elements from the stream. So, if I call drain() twice, the second time I won't get any results.  That's why I added inspect(). 

Are you trying to enforce that the tuples in the stream can only be accessed once?

**Comment by pbailis** [comment]
@raininthesun Yes, the goal is to never expose the internals of the stream interface to the consumer. Right now, we only support exactly once draining. My PR (#133) refactors your code to behave correctly despite this behavior.

**Comment by pbailis** [comment]
Fixed in #133
