### ISSUE TITLE
Static Threshold for different outlier detectors

### ISSUE THREAD

**Issue by raininthesun** [stanford-futuredata/macrobase#138]
@pbailis @mamikonyana 

I understand we've added more outlier detectors, and each one of them has a score() function that returns a score for every datum. The scores are used by outlier classifiers. If we are to use percentile classifier, it's no problem. However, if we are to use static threshold classifier, I am not exactly sure what should be the right threshold `macrobase.analysis.classify.outlierStaticThreshold` for every outlier detector.

For example, for MAD, the recommended threshold is 3. Can we have a recommended threshold for each detector?  We can encode the default threshold values in MacroBaseConf.java; or we can simply document it in docs/parameter_desc.md

**Comment by mamikonyana** [comment]
I added #139 this should help a little with your problem.

**Comment by pbailis** [comment]
@raininthesun: does this + the conversation we had on Friday address your concerns?

**Comment by raininthesun** [comment]
@pbailis @mamikonyana Yes!
