### ISSUE TITLE
Error when running bin/server.sh: relation "sensor_data" does not exist

### ISSUE THREAD

**Issue by qiuyij** [stanford-futuredata/macrobase#143]
When I was running bin/server.sh it gave me
`ERROR [2016-05-28 18:53:09,969] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 885c3f33ae9ed907
! org.postgresql.util.PSQLException: ERROR: relation "sensor_data" does not exist
!   Position: 15
! at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1104-jdbc41.jar:na]
! at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1104-jdbc41.jar:na]
! at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1104-jdbc41.jar:na]
! at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:562) ~[postgresql-9.3-1104-jdbc41.jar:na]
! at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:406) ~[postgresql-9.3-1104-jdbc41.jar:na]
! at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:286) ~[postgresql-9.3-1104-jdbc41.jar:na]
! at macrobase.ingest.SQLIngester.getSchema(SQLIngester.java:100) ~[classes/:na]
! at macrobase.runtime.resources.SchemaResource.getSchema(SchemaResource.java:27) ~[classes/:na] `

I'm not quite sure what went wrong. Postgresql outputted the following
`$ postgres --config_file=/usr/localpath/var/postgres/postgresql.conf` 
`LOG:  MultiXact member wraparound protections are now enabled`
`LOG:  database system is ready to accept connections`
`LOG:  autovacuum launcher started`
`ERROR:  relation "sensor_data" does not exist at character 15`
`STATEMENT:  SELECT * from sensor_data LIMIT 1`

I suppose the correct query should be `SELECT * from sensor_data_demo LIMIT 10;`? But how come in `SQLIngester.java`:
`Statement stmt = connection.createStatement();`
`String sql = String.format("%s LIMIT 1", removeSqlJunk(removeLimit(baseQuery)));`
`ResultSet rs = stmt.executeQuery(sql);`
it didn't get the right string? Hard coding didn't help much since there are other places associated with the use of `sql` that have the same problem.

Thanks!

**Comment by qiuyij** [comment]
Postgresql outputted the following
`$ postgres --config_file=/usr/localpath/var/postgres/postgresql.conf 
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  relation "sensor_data" does not exist at character 15
STATEMENT:  SELECT * from sensor_data LIMIT 1`

**Comment by pbailis** [comment]
It appears that you've specified `sensor_data` as the target table in your configuration, but no such table exists in Postgres. You should be able to verify this by running `psql` and executing `\d`.

If you want to run MacroBase over a given table, input a `SELECT` statement over the table.

You can load some sample data using the tutorial: https://github.com/stanford-futuredata/macrobase/wiki/Tutorial

**Comment by qiuyij** [comment]
I think my `psql postgres` outputs the correct messages
`postgres=# \d`
`            List of relations`
`Schema |       Name       | Type  | Owner `
`--------+------------------+-------+-------`
`public | sensor_data_demo | table | qjia`
`(1 row)`
It just didn't get the correct statement for some reason; instead of receiving `SELECT * from sensor_data_demo LIMIT 10;` which would have worked, it received `SELECT * from sensor_data LIMIT 1`

**Comment by pbailis** [comment]
After modifying the "Base query" form in the GUI, try clicking the "submit" button. The original base query may be getting cached.

**Comment by qiuyij** [comment]
Thanks! That worked out well!

By the way, this screenshot in the tutorial is just a little imprecise; although the description above says "SELECT * FROM sensor_data_demo;", in the screenshot it's "SELECT * FROM sensor_data;"
![screen shot 2016-05-28 at 5 51 57 pm](https://cloud.githubusercontent.com/assets/6559964/15630748/1ad207a2-24fd-11e6-984d-58c687ff595d.png)
