### ISSUE TITLE
ValueError when running scripts/py_analysis/analyze_apriori.py

### ISSUE THREAD

**Issue by qiuyij** [stanford-futuredata/macrobase#146]
I have python 2.7.10, pandas 0.18.1, numpy 1.8.0rc1.
When I ran
`python scripts/py_analysis/analyze_apriori.py`
it said
`Traceback (most recent call last):`
`  File "script/py_analysis/analyze_apriori.py", line 4, in <module>`
`    from sklearn import linear_model, cluster`
`  File "/Library/Python/2.7/site-packages/sklearn/__init__.py", line 57, in <module>`
`    from .base import clone`
`  File "/Library/Python/2.7/site-packages/sklearn/base.py", line 11, in <module>`
`    from .utils.fixes import signature`
`  File "/Library/Python/2.7/site-packages/sklearn/utils/__init__.py", line 10, in <module>`
`    from .murmurhash import murmurhash3_32`
`  File "numpy.pxd", line 155, in init sklearn.utils.murmurhash (sklearn/utils/murmurhash.c:5029)`
`ValueError: numpy.dtype has the wrong size, try recompiling`

Is it the version of the module that's causing the error? Which versions am I supposed to use? Thanks!

**Comment by pbailis** [comment]
Interesting, thanks!

Two comments:

1.) In general, the `analyze` directory isn't really supported. It's largely a place for scripts, many of which haven't been run for a while and should be deleted. What are you trying to accomplish here?
2.) The following post recommends a clean uninstall followed by a clean install of numpy and pandas: https://github.com/sloria/TextBlob/issues/62#issuecomment-201119113

**Comment by qiuyij** [comment]
Sure thing!

1) I was browsing around. I ran `analyze_apriori.py` mainly because I was curious to see how the apriori part works in action and fits into the code base.
2) I'll try that although I thought I did something similar yesterday. Thanks!

**Comment by qiuyij** [comment]
May I ask something else?

I was running `bin/streaming.sh` and tracing the function calls to get a better understanding of the code, and
1) `SQLIngester.java` uses frequently these terms `contextualDiscreteAttrValues`, `contextualDoubleAttrValues`, `auxilaryAttributes`. Is there a more detailed explanation about these terms? I'm interested to know how the streaming and ingesting part works.
2) In the `pipeline` folder, there are `BasicBatchedPipeline`, `BasicContextualBatchedPipeline`, `BasicOneShotEWStreamingPipeline`, `GridDumpingPipeline`, and `MixtureModelPipeline`, for customization I think? `BasicBatchedPipeline` and `BasicOneShotEWStreamingPipeline` look straightforward. Can I ask for more explanation about the other three? Higher-level speaking, in what aspects do they differ and relate to each other?

Thanks a million!

**Comment by edgan8** [comment]
Oh man, @mamikonyana is the expert on the mixturemodel and griddumping and @raininthesun is working on the "contextual" components. They're definitely more on the experimental side and you can get pretty far by focusing on the BasicBatchedPipeline and BasicOneShotEW pipeline.

**Comment by pbailis** [comment]
@edgan8 @qiuyij: let's continue to follow up via Skype. Closing for now, feel free to reopen if needed.
