### ISSUE TITLE
Error while processing index page request

### ISSUE THREAD

**Issue by subhasri10** [stanford-futuredata/macrobase#165]
I simply installed on my linux box, started the server and tried to access the GUI. DB table sensor_data_demo is created and it has the data as well. But I'm getting the following error on the base page itself.
![macrobase](https://cloud.githubusercontent.com/assets/19743522/18429773/e19dc440-78f2-11e6-8348-5dc9bcf03eb5.png)

**Comment by pbailis** [comment]
This looks like an issue with the database connection. Can you verify that you've provided the correct hostname and port (e.g., `localhost:555`) in the `Database URL` field?

**Comment by subhasri10** [comment]
That is precisely my question. Where all do we specify the DB url? Only in 
GUI  home page or is there any config file? I could not find it in 
tutorial.

Thanks & Regards
Subhasri Duttagupta
Tata Consultancy Services
Mailto: subhasri.duttagupta@tcs.com
Website: http://www.tcs.com
____________________________________________
Experience certainty.   IT Services
                        Business Solutions
                        Consulting
____________________________________________

**Comment by pbailis** [comment]
The GUI has a "Database URL" field that you can use to specify the hostname and port:
![image](https://cloud.githubusercontent.com/assets/970191/18461795/07072138-7932-11e6-99f1-c1060c9abb8d.png)

Have you tried modifying the hostname in the UI? You may need to scroll down beyond the error message to see the dialog box.

If needed, you can also modify `conf/server.yaml` to provide additional parameters like username and password, however I don't think this is needed right now:
https://github.com/stanford-futuredata/macrobase/blob/master/docs/parameters_desc.md#workload-specific-parameters

**Comment by pbailis** [comment]
Addressed offline.
