### ISSUE TITLE
Address already in use [reopening]

### ISSUE THREAD

**Issue by kemathur** [stanford-futuredata/macrobase#173]
Hello,

Sorry for again posting this but the fix presented here:

https://github.com/stanford-futuredata/macrobase/issues/170

Did not work for me. Reposting the error after the fix:

```
* Failed to parse configuration at: server.applicationConnectors.[0]; Could not resolve type id 'http' into a subtype of [simple type, class io.dropwizard.jetty.ConnectorFactory]: known type ids = [ConnectorFactory]
 at [Source: N/A; line: -1, column: -1] (through reference chain: macrobase.conf.MacroBaseConf["server"]->io.dropwizard.server.DefaultServerFactory["applicationConnectors"]->java.util.ArrayList[0])
```

**Comment by sweatybridge** [comment]
Can you rename the issue as the error produced is different from #170 

You can try the solution here:
http://stackoverflow.com/questions/27543060/why-does-dropwizard-configuration-is-not-working

**Comment by pbailis** [comment]
@kemathur please let us know if you still have this issue
