### ISSUE TITLE
Issue with demo / Null Pointer Exception

### ISSUE THREAD

**Issue by burkaygur** [stanford-futuredata/macrobase#185]
Found two issues with the tutorial:

1) python script/load_demo.py, the load_demo.py is now located under tools/
2) got the following error trying to run the tutorial

0.2883.95 Safari/537.36" 2
0:0:0:0:0:0:0:1 - - [16/Jan/2017:00:35:35 +0000] "GET /fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 304 - "http://localhost:8080/css/bootstrap.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36" 3
ERROR [2017-01-16 00:35:35,663] macrobase.runtime.resources.SchemaResource: An error occurred while processing a request:
! java.lang.NullPointerException: null
! at macrobase.runtime.resources.SchemaResource.getSchema(SchemaResource.java:42) ~[classes/:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
! at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336) [macrobase-assembly-0.1-SNAPSHOT.jar:na]

**Comment by pbailis** [comment]
Thanks! First issue should now be fixed.

Second issue: I now have a fix for this so the null pointer exception shouldn't occur. However, for now, just make sure that you have `Base Query` filled out and you press "submit" before you click "Analyze".

Thanks!
P
