### ISSUE TITLE
Unable to run mvn package 

### ISSUE THREAD

**Issue by aksavla** [stanford-futuredata/macrobase#207]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] macrobase ......................................... SUCCESS [0.002s]
[INFO] macrobase-legacy .................................. FAILURE [2.006s]
[INFO] macrobase-frontend ................................ SKIPPED
[INFO] macrobase-contrib ................................. SKIPPED
[INFO] macrobase-assembly ................................ SKIPPED
[INFO] macrobase ......................................... SKIPPED
[INFO] macrobase ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.188s
[INFO] Finished at: Wed Jul 19 11:48:56 PDT 2017
[INFO] Final Memory: 12M/213M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project macrobase-legacy: Fatal error compiling: invalid target release: 1.8 -> [Help 1]

**Comment by edgan8** [comment]
Hi @aksavla thanks for the report. Do you have jdk 1.8 installed?

**Comment by aksavla** [comment]
Yes, I got that working but now have a java.net.BindException: Address already in use error. I tried editing the  conf/macrobase.yaml per https://github.com/stanford-futuredata/macrobase/issues/170 and get the same error.

**Comment by edgan8** [comment]
@aksavla can you copy paste the exact error message here?

**Comment by aksavla** [comment]
+ java -cp 'legacy/target/classes:frontend/target/classes:frontend/src/main/resources/:contrib/target/classes:assembly/target/*:' macrobase.runtime.MacroBaseServer server conf/macrobase.yaml
INFO  [2017-08-01 19:28:47,228] org.eclipse.jetty.util.log: Logging initialized @4721ms
INFO  [2017-08-01 19:28:47,521] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: assets for path /*
INFO  [2017-08-01 19:28:47,952] io.dropwizard.server.ServerFactory: Starting macrobase
INFO  [2017-08-01 19:28:47,977] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2017-08-01 19:28:48,017] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2017-08-01 19:28:48,332] org.eclipse.jetty.setuid.SetUIDListener: Opened application@3b220bcb{HTTP/1.1}{0.0.0.0:8080}
WARN  [2017-08-01 19:28:48,341] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED org.eclipse.jetty.server.Server@652a7737: java.lang.RuntimeException: java.net.BindException: Address already in use
! java.net.BindException: Address already in use
! at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_66]
! at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_66]
! at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_66]
! at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_66]
! at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_66]
! at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321) ~[macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:200) ~[macrobase-assembly-0.1-SNAPSHOT.jar:na]
! ... 8 common frames omitted
! Causing: java.lang.RuntimeException: java.net.BindException: Address already in use
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:213) ~[macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188) ~[macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67) ~[macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at io.dropwizard.Application.run(Application.java:80) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:22) [classes/:na]
ERROR [2017-08-01 19:28:48,341] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.net.BindException: Address already in use
! at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_66]
! at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_66]
! at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_66]
! at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_66]
! at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_66]
! at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321) ~[macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:200) ~[macrobase-assembly-0.1-SNAPSHOT.jar:na]
! ... 8 common frames omitted
! Causing: java.lang.RuntimeException: java.net.BindException: Address already in use
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:213) ~[macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188) ~[macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67) ~[macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) ~[macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at io.dropwizard.Application.run(Application.java:80) [macrobase-assembly-0.1-SNAPSHOT.jar:na]
! at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:22) [classes/:na]
Exception in thread "main" java.lang.RuntimeException: java.net.BindException: Address already in use
        at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:213)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
        at io.dropwizard.cli.Cli.run(Cli.java:70)
        at io.dropwizard.Application.run(Application.java:80)
        at macrobase.runtime.MacroBaseServer.main(MacroBaseServer.java:22)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
        at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:200)
        ... 8 more

**Comment by esmailoghli** [comment]
You can just skip the tests and then it compiles but it doesn't solve the problem because there is an error in the code. when I'm gonna run the bin/frontend.sh I get ArrayIndexOutOfBoundException.
`mvn package -Dmaven.test.skip=true`

**Comment by esmailoghli** [comment]
I found out the problem. JAVA VERSION. 
It is not working with java version 11 (mine) then I check it with version 8 and it worked properly.

**Comment by fabuzaid21** [comment]
Yep, we currently only support Java 1.8.
