### ISSUE TITLE
Tutorial:  Cannot view in  http://localhost:8080/

### ISSUE THREAD

**Issue by ravii2001** [stanford-futuredata/macrobase#212]
Hi

I installed macrobase, postgres and started the macrobase server.  But cannot view MacroBase Exploratory GUI.  I am getting "can't connect to local host" error when trying http://localhost:8080/ .

$ bin/server.sh
11:19:44.764 DEBUG s.r.Routes - Adds route: post, /query, spark.ResponseTransformerRouteImpl$1@7c30a502
11:19:44.778 INFO  o.e.j.u.log - Logging initialized @342ms
11:19:44.825 INFO  s.e.j.EmbeddedJettyServer - == Spark has ignited ...
11:19:44.825 INFO  s.e.j.EmbeddedJettyServer - >> Listening on 0.0.0.0:4567
11:19:44.827 INFO  o.e.j.s.Server - jetty-9.3.z-SNAPSHOT
11:19:44.889 INFO  o.e.j.s.ServerConnector - Started ServerConnector@68329845{HTTP/1.1,[http/1.1]}{0.0.0.0:4567}
11:19:44.889 INFO  o.e.j.s.Server - Started @456ms

**Comment by pbailis** [comment]
Thanks for bringing this to our attention. The GUI command recently changed, and we just updated the wiki in response to your issue.

Try instead running `bin/frontend.sh`.
