### ISSUE TITLE
Can't view pictures in tutorial

### ISSUE THREAD

**Issue by madcarrot** [stanford-futuredata/macrobase#247]
Pictures on the tutorial page failed to load:
![image](https://user-images.githubusercontent.com/3460073/35861743-1acd9760-0b17-11e8-90e0-1a04780c50f4.png)

I'm using Chrome (Version 63.0.3239.132) on Mac (10.12.6).

**Comment by AlexP11223** [comment]
It works fine for me, probably it's something on your side.

Check DevTools coonsole.

**Comment by madcarrot** [comment]
@AlexP11223 Thanks for your response! I think I realized the problem:

The pictures in the [Tutorial](https://github.com/stanford-futuredata/macrobase/wiki/Tutorial) Wiki page work fine, but the [Tutorial](http://macrobase.stanford.edu/docs/user-guide/tutorial/#overview) linked from the [Macrobase Homepage](http://macrobase.stanford.edu/) are down. Would you mind checking that? I've tried with both my laptop and my phone so it's less likely to be something from my side.

**Comment by AlexP11223** [comment]
Yes, it doesn't work there. 

I guess they need to either copy these images to that server or change links to use the images hosted in this GitHub repo (currently they are relative, so it tried to access non-existing images on http://macrobase.stanford.edu).

**Comment by madcarrot** [comment]
Looks like the image links are fixed: https://macrobase.stanford.edu/docs/gui/tutorial/
