### ISSUE TITLE
CSVDataFrameParser fails on null in double columns

### ISSUE THREAD

**Issue by AlexP11223** [stanford-futuredata/macrobase#258]
`CSVDataFrameParser` from `lib` throws `NullPointerException` on datasets with numeric columns containing `null`.

Possible fix:

```diff
--- a/lib/src/main/java/edu/stanford/futuredata/macrobase/ingest/CSVDataFrameParser.java
+++ b/lib/src/main/java/edu/stanford/futuredata/macrobase/ingest/CSVDataFrameParser.java
@@ -111,7 +111,7 @@ public class CSVDataFrameParser implements DataFrameLoader {
                         stringColumns[stringColNum++].add(rowValue);
                     } else if (t == Schema.ColType.DOUBLE) {
                         try {
-                            doubleColumns[doubleColNum].add(Double.parseDouble(rowValue));
+                            doubleColumns[doubleColNum].add(rowValue == null ? Double.NaN : Double.parseDouble(rowValue));
                         } catch (NumberFormatException e) {
                             doubleColumns[doubleColNum].add(Double.NaN);
                             doubleParseFailures++;
```

By the way, it was difficult to find the source of this error because MacroBase SQL `QueryEngine` `importTableFromCsv` rethrows exception with just the message. So I would get output like this:

```
IMPORT FROM CSV FILE .....................
null
```

Maybe it should preserve and output the stack trace?

**Comment by fabuzaid21** [comment]
Thanks @AlexP11223! I just pushed a fix for this bug—I also changed the exception handling in `MacroBaseSQLRepl` to print the stacktrace, as you suggested. If you pull the latest code on master you shouldn't see these problems anymore.
