### ISSUE TITLE
Question on MacrobaseSQL Syntax and Schema

### ISSUE THREAD

**Issue by garrisonhess** [stanford-futuredata/macrobase#267]
Hi,

I got MacrobaseSQL running on a docker container, thanks to the nice setup and tutorial pages.  I loaded the wikipedia dataset into MacrobaseSQL, and ran some test queries from the tutorial documentation.  When I went to improvise with my own queries, which were comparatively fancy, I got java runtime errors that exited Macrobase-SQL.  When I restarted MacrobaseSQL, the wiki table had disappeared.  When I queried the information_schema.tables system table to show me what objects exist on the database, I found out that table doesn't exist.  Similarly, when I ran "SELECT current_database();" so I could see what database I am in by default, I got a Java "No value present" error.  It seems I'm off base with how I'm approaching some of this.

My questions are:
1.  Should MacrobaseSQL be capable of running essentially any PostgreSQL query?  That's the way it seemed from using Postgres in the Macrobase GUI setup, but maybe this is not the case.
2.  How do I persist a table in the system, like wiki, such that I don't have to run the insert statement every time to build the table and then read/analyze it?
3.  Why is there no information_schema and why can't I use SELECT current_database()?
4.  I am planning on loading a lot of relational data across multiple tables into macrobase, and have a solid analytical plan for dissecting the data into appropriate questions for the engine to answer.  However, this requires my ability to read and transform the relational tables with a lot of flexibility.  How am I supposed to go about using advanced SQL scripts with MacrobaseSQL?

Sorry if some of this is unclear.  I've never worked with anything like this before.

Thanks!

Garrison Hess

**Comment by ganesh-srinivas** [comment]
Hi. I'm not the project maintainer, I'm just another user who runs a lot of custom PostgreSQL queries regularly. May I suggest using MacroBase in batch or streaming mode? The PostgreSQL query for the input data must be provided in the configuration file. 

`macrobase.loader.db.baseQuery: SELECT * from (select A, B, C, D, E FROM my_table order by timestamp offset 0 limit 1500000) f;`

MacroBase can then be run in the following way (batch mode run command shown below, streaming is similar):
`bin/batch.sh conf/batch.yaml | tee 3jul2018_batch_macrobase_report.txt`

It is straightforward to modify the source code to accept static upper and lower thresholds. The patterns/explanations in the output report are well-formatted. This makes it easy to plot histograms and thresholds (much more intuitive for an audience not acquainted with data analysis).
