### ISSUE TITLE
test failure while building macrobase

### ISSUE THREAD

**Issue by rameshtocode** [stanford-futuredata/macrobase#273]
Hi - I am trying to run GUI version of macrobase and while building the application I am getting following test error.
-----------
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.347 s <<< FAILURE! - in macrobase.runtime.MacroBaseApplicationTest
[ERROR] simpleTest(macrobase.runtime.MacroBaseApplicationTest)  Time elapsed: 0.346 s  <<< ERROR!
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at macrobase.runtime.MacroBaseApplicationTest.simpleTest(MacroBaseApplicationTest.java:18)
--------
Even if I go ahead by suppressing the test runs...application gets built but while running the frontend.sh I get the same issue. am attaching the full trace of the build

[out.txt](https://github.com/stanford-futuredata/macrobase/files/2894476/out.txt)

**Comment by rameshtocode** [comment]
Issue got fixed....Issue was java version.

**Comment by Benature** [comment]
@rameshtocode Hi, I have the same issue, what version did you use when u encountered the `test failures`? (I am using JDK14.0.2)
