### ISSUE TITLE
Remove MemoryCachingLoader

### ISSUE THREAD

**Issue by pbailis** [stanford-futuredata/macrobase#37]
Is a hack and is not reliable. The DiskCachingLoader does pretty well as-is.

**Comment by deepakn94** [comment]
Sorry, you probably already told me this, but what does the MemoryCachingLoader do?

**Comment by pbailis** [comment]
It was an earlier version of the DiskCachingLoader that stores datasets in memory. I was using it to pre-populate datasets for the GUI. It is more clever than the DiskCachingLoader and tries to reuse columns if they're already loaded, though it turned into an abomination in the process :)
