### ISSUE TITLE
Add configuration option to disable timing information.

### ISSUE THREAD

**Issue by pbailis** [stanford-futuredata/macrobase#40]
It's unclear how to do this cleanly.

**Comment by pbailis** [comment]
Despite [this post](https://groups.google.com/forum/#!searchin/metrics-user/performance/metrics-user/CHk14cMmLsM/Gkk-XxhNOSgJ), [in our inner streaming loop](https://github.com/stanford-futuredata/macrobase/blob/a9de8efad453638eeab156cf4f36dbaac0532cf0/src/main/java/macrobase/analysis/StreamingAnalyzer.java#L175), the timers can be expensive (empirically, 30+% overhead).

**Comment by deepakn94** [comment]
This happens when we run MCD too? I would be surprised if that were the case.
I think MAD is too light-weight to profile effectively, in all likelohood.

**Comment by pbailis** [comment]
Fixed by https://github.com/stanford-futuredata/macrobase/commit/f76a465530a4bcac6cc525908a1669da9a476168.
