### ISSUE TITLE
Refactoring discussion: Configuration

### ISSUE THREAD

**Issue by pbailis** [stanford-futuredata/macrobase#76]
Right now, we have config file spaghetti. We have a large number of config parameters, each of which is set manually for:
 * `BaseAnalyzer` (https://github.com/stanford-futuredata/macrobase/blob/f76a465530a4bcac6cc525908a1669da9a476168/src/main/java/macrobase/analysis/BaseAnalyzer.java#L38)
 * `StreamingAnalyzer` (https://github.com/stanford-futuredata/macrobase/blob/f76a465530a4bcac6cc525908a1669da9a476168/src/main/java/macrobase/analysis/StreamingAnalyzer.java#L48)

This leads to pretty ugly code like:
https://github.com/stanford-futuredata/macrobase/blob/f76a465530a4bcac6cc525908a1669da9a476168/src/main/java/macrobase/runtime/standalone/streaming/MacroBaseStreamingCommand.java#L36

Do we want to keep this code as is or should we make the config objects generic and pass them into each analyzer?

**Comment by pbailis** [comment]
See Spark, which uses untyped Key-Value pairs: https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/SparkConf.scala#L30

**Comment by viveksjain** [comment]
IMO KV pairs seem like they would scale much better to more config flags, which is inevitable as the codebase progresses. Not sure how exactly the untyped stuff would work in Java though. And we would need to keep good, up-to-date documentation on all the config options in one file.

**Comment by pbailis** [comment]
Spark has a good example of typing:

`Double getDouble(String param)`, `String getString(String param)`

It gets a little annoying to have a bunch of these, like `List<String> getStringList(String param)`

You can imagine also having:

`Double getDoubleOrElse(String param, Double default)`

And:

`Boolean mandatoryParams(List<String> params)`.

**Comment by pbailis** [comment]
I started writing a new config class. Two things:
  1. Do we want to rename all `MacroBase` files to `Macrobase`?
  2. Spark's configuration API forces you to specify a default for each setting. The upside of this is it makes the behavior explicit. The downside is that this makes it awkward to enforce mandatory fields (e.g., `targetLowMetrics`). Which do we prefer?

https://github.com/stanford-futuredata/macrobase/commit/751ae21dd5b2762c18679aef0a834958f4193d9c#diff-a68be5bcbbbf7f3d53f49b90310d3e59R11

**Comment by deepakn94** [comment]
I like the idea of defaults for the most part, since most of our parameters _do_ have default values. For those that don't, we can have a default value like `null`, and then throw an exception if any argument is `null`.

**Comment by mamikonyana** [comment]
I like defaults too. the only thing that we require are the sql query, metrics and attributes. and those seem hard to forget :)
Also since we are moving to automating everything, we should in the end have defaults for everything, no?

**Comment by pbailis** [comment]
See #77.
