### ISSUE TITLE
Re-scale metrics upon ingest.

### ISSUE THREAD

**Issue by pbailis** [stanford-futuredata/macrobase#9]
For consistency across datasets and possibly improved convergence time, re-scale our metrics to a [0, 1] scale upon ingest. To start, let's do (x-min(X))/(max(X)-min(X)).

**Comment by pbailis** [comment]
We may want to revisit this if it doesn't fix some of the weird C-Step behavior in MCD we were seeing.

**Comment by deepakn94** [comment]
C-Step behavior?

**Comment by pbailis** [comment]
The inner loop in FastMCD: https://github.com/stanford-futuredata/macrobase/blob/master/src/main/java/macrobase/analysis/outlier/MinCovDet.java#L209
