### ISSUE TITLE
Set contextual attributes via conf

### ISSUE THREAD

**Issue by pbailis** [stanford-futuredata/macrobase#92]
`DataLoader` pulls metrics and attributes from the `conf` object: https://github.com/stanford-futuredata/macrobase/blob/master/src/main/java/macrobase/ingest/DataLoader.java#L32

However, the contextual attributes are passed in via `getData` (https://github.com/stanford-futuredata/macrobase/blob/master/src/main/java/macrobase/ingest/DataLoader.java#L55).

@raininthesun: is there a reason why this needs to be the case? Can we refactor to load the contextual attributes like the rest?

**Comment by raininthesun** [comment]
The reason for that design is that the contextual attributes should not be specified in the conf file eventually, but should be inferred automatically, so I created a separate getData interface. Now that I think about it, we can still infer that before invoking getData. 

I will change it.
