### ISSUE TITLE
Abstract trained model of an outlier detector for reuse 

### ISSUE THREAD

**Issue by raininthesun** [stanford-futuredata/macrobase#98]
I'd like to reuse a model trained for Context C1 to be reused for Context C2, i.e., I don't want to run the ` public abstract void train(List<Datum> data);` in class   `public abstract class BatchTrainScore` every time for a context. 

I propose the following to achieve this

- I add an interface called `public interface BatchModel` , and another training method `public abstract void train(BatchModel batchModel);` in  `public abstract class BatchTrainScore ` . `public interface BatchModel` is supposed to contain all the information about a model, for example, it contains median, MAD for MADDetector. 

- for every implementation of `BatchTrainScore ` (MAD, KDE), we add an implementation of `public interface BatchModel`, that contains the model specific to them, as well as an implementation of `public abstract void train(BatchModel batchModel);`.

Here is an example implementation of MAD:

https://github.com/stanford-futuredata/macrobase/blob/trainedModelAbstraction/src/main/java/macrobase/analysis/stats/BatchTrainScore.java

https://github.com/stanford-futuredata/macrobase/blob/trainedModelAbstraction/src/main/java/macrobase/analysis/stats/MAD.java

**Comment by pbailis** [comment]
Dumb question: if you want to reuse a trained model, can't you just call the model's `score` function on new data? 

I understand that https://github.com/stanford-futuredata/macrobase/blob/trainedModelAbstraction/src/main/java/macrobase/analysis/stats/MAD.java#L35 allows nicer getters/setters, but am not sure why we need it compared just calling `score`.

**Comment by raininthesun** [comment]
You are absolutely right! I can just call the model's score function on new data. This means that every context would have to store a deep copy of the OutlierDetector object. 

Previously, my design was that all contexts shares an OutlierDetector object, and every context just needs to store its copy of the trained model of the OutlierDetector object. 

They work the same way! But your suggestion has less code disruption. Thanks for pointing it out! I will go with your suggestion.

**Comment by pbailis** [comment]
@raininthesun: glad to hear it! Thanks for sketching this out so I understand what you're trying to do. :)
